"""
argos.vision.detector -- Real-time defect detection using ONNX inference.

Loads a quantised ONNX model and runs single-shot detection on camera
frames, returning bounding boxes annotated with defect type labels.
Supports NautilusQuant INT8 models via a dequantisation look-up table.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Sequence

import numpy as np
import onnxruntime as ort

from argos.config import EdgeProcessorConfig


class DefectType(str, Enum):
    """Enumeration of detectable hull and machinery defect categories."""

    CORROSION = "corrosion"
    CRACK = "crack"
    FOULING = "fouling"
    LEAK = "leak"
    DEFORMATION = "deformation"


@dataclass(frozen=True)
class Detection:
    """Single detection result with spatial and semantic metadata."""

    x_min: float
    y_min: float
    x_max: float
    y_max: float
    defect_type: DefectType
    confidence: float


@dataclass
class NautilusQuantLUT:
    """Stub for NautilusQuant INT8 dequantisation look-up table.

    The production LUT is generated by ``nautilusquant calibrate`` and
    maps each INT8 activation bin to its FP32 equivalent.  This stub
    provides identity passthrough for FP32 models.
    """

    scale: np.ndarray = field(default_factory=lambda: np.array([1.0], dtype=np.float32))
    zero_point: np.ndarray = field(default_factory=lambda: np.array([0], dtype=np.int8))

    def dequantize(self, tensor: np.ndarray) -> np.ndarray:
        """Convert INT8 tensor to FP32 using calibration parameters."""
        return (tensor.astype(np.float32) - self.zero_point.astype(np.float32)) * self.scale


class DefectDetector:
    """Edge-deployed defect detector backed by ONNX Runtime.

    Parameters
    ----------
    config:
        Edge processor configuration including model path and thresholds.
    """

    _LABEL_MAP: dict[int, DefectType] = {
        0: DefectType.CORROSION,
        1: DefectType.CRACK,
        2: DefectType.FOULING,
        3: DefectType.LEAK,
        4: DefectType.DEFORMATION,
    }

    def __init__(self, config: EdgeProcessorConfig | None = None) -> None:
        self._cfg = config or EdgeProcessorConfig()
        self._lut = NautilusQuantLUT()
        self._session = ort.InferenceSession(
            self._cfg.detector_model_path,
            providers=[self._cfg.execution_provider],
        )
        self._input_name: str = self._session.get_inputs()[0].name

    def preprocess(self, frame: np.ndarray) -> np.ndarray:
        """Resize, normalise, and transpose a BGR frame to NCHW float32."""
        import cv2

        h, w = self._cfg.input_size
        resized = cv2.resize(frame, (w, h))
        blob = resized.astype(np.float32) / 255.0
        blob = np.transpose(blob, (2, 0, 1))[np.newaxis, ...]
        return blob

    def _apply_nms(
        self, boxes: np.ndarray, scores: np.ndarray
    ) -> np.ndarray:
        """Greedy non-maximum suppression returning kept indices."""
        x1, y1, x2, y2 = boxes[:, 0], boxes[:, 1], boxes[:, 2], boxes[:, 3]
        areas = (x2 - x1) * (y2 - y1)
        order = scores.argsort()[::-1]
        keep: list[int] = []
        while order.size > 0:
            i = order[0]
            keep.append(int(i))
            xx1 = np.maximum(x1[i], x1[order[1:]])
            yy1 = np.maximum(y1[i], y1[order[1:]])
            xx2 = np.minimum(x2[i], x2[order[1:]])
            yy2 = np.minimum(y2[i], y2[order[1:]])
            inter = np.maximum(0.0, xx2 - xx1) * np.maximum(0.0, yy2 - yy1)
            iou = inter / (areas[i] + areas[order[1:]] - inter + 1e-6)
            remaining = np.where(iou <= self._cfg.nms_iou_threshold)[0]
            order = order[remaining + 1]
        return np.array(keep, dtype=np.intp)

    def detect(self, frame: np.ndarray) -> Sequence[Detection]:
        """Run detection on a single BGR frame.

        Returns a list of ``Detection`` objects filtered by confidence
        threshold and non-maximum suppression.
        """
        blob = self.preprocess(frame)
        raw_output = self._session.run(None, {self._input_name: blob})[0]
        raw_output = self._lut.dequantize(raw_output)
        # Expected shape: (1, N, 5+C) -- x1,y1,x2,y2,obj_conf,cls_scores...
        preds = raw_output[0]
        obj_conf = preds[:, 4]
        mask = obj_conf >= self._cfg.confidence_threshold
        preds = preds[mask]
        if preds.shape[0] == 0:
            return []

        boxes = preds[:, :4]
        class_ids = np.argmax(preds[:, 5:], axis=1)
        scores = preds[:, 4] * np.max(preds[:, 5:], axis=1)
        keep = self._apply_nms(boxes, scores)

        detections: list[Detection] = []
        for idx in keep:
            cls_id = int(class_ids[idx])
            if cls_id not in self._LABEL_MAP:
                continue
            detections.append(
                Detection(
                    x_min=float(boxes[idx, 0]),
                    y_min=float(boxes[idx, 1]),
                    x_max=float(boxes[idx, 2]),
                    y_max=float(boxes[idx, 3]),
                    defect_type=self._LABEL_MAP[cls_id],
                    confidence=float(scores[idx]),
                )
            )
        return detections
